### PR TITLE
percentage support

### PR DESCRIPTION
**Pull request by thost96**
Added support for iframe width and height in percentage.

### CODE REVIEW

**Comment by mwittig** [comment]
That's great! However, I am little concerned about the changes as they might break the scaling feature. Did you test all features?

**Comment by thost96** [comment]
I reviewed it again and fixed the scale function. Works fine now. All other features are also tested and work fine.

**Comment by mwittig** [comment]
Excellent! I'll also try to do some testing tonight.

**Comment by bstrebel** [comment]
Tried to test the new function but pimatic dies with a [stacktrace](https://github.com/Oitzu/pimatic-iframe/files/606147/stacktrace.txt) when I save a new iframeDevice in the mobile frontend :-(

**Comment by bstrebel** [comment]
A very simple [approach](https://github.com/bstrebel/pimatic-iframe/tree/develop) works for me with appealing layout at 99.5% iframe width and is compatible with the original iframeDevice attributes.

**Comment by mwittig** [comment]
@Oitzu Why did you merge it? It does not work as expected!

**Comment by Oitzu** [comment]
@mwittig thanks for the note! I somehow misread something.
I didn't published it yet, because i hadn't tested it myself.
I reverted the pull-request for now, and will clean up the mess in the evening.

**Comment by Oitzu** [comment]
Cleaned it up a little. Master is back to original state.
Changes are in the branch "percentage-support".

**Comment by cm86** [comment]
hello, is this working now? (would be great... ;) )

**Comment by mwittig** [comment]
No, it doesn't.
Please be patient.  I'll look into this asap

**Pull request merged**
